# Executes commands at the start of an interactive session.

source /usr/local/share/antigen/antigen.zsh

# iTerm
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
iterm2_print_user_vars() { 
    iterm2_set_user_var gitBranch $( (git branch 2> /dev/null) | grep \* | cut -c3-) 
}

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# ** PATH **

# JB
PATH=$HOME/miniconda3/bin:$PATH:/usr/local/sbin
# mysql (homebrew)
PATH=/usr/local/opt/mysql@5.7/bin:$PATH
# Macports
PATH=$PATH:/opt/local/bin:/opt/local/sbin  
export PATH

# source ${HOME}/.gobotRC
source ${HOME}/.aliases.zsh

## zsh options
setopt EXTENDED_GLOB
export EDITOR='vim'
# bindkey -v

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# conda
source activate py35

# ** prompt **

zstyle ':prezto:module:prompt' theme 'spaceship'

# spaceship prompt options
SPACESHIP_PROMPT_ORDER=(
#    time          # Time stampts section
    user          # Username section
    dir           # Current directory section
    host          # Hostname section
    git           # Git section (git_branch + git_status)
#    hg            # Mercurial section (hg_branch  + hg_status)
#    package       # Package version
#    node          # Node.js section
#    ruby          # Ruby section
#    elixir        # Elixir section
#    xcode         # Xcode section
#    swift         # Swift section
#    golang        # Go section
#    php           # PHP section
#    rust          # Rust section
#    haskell       # Haskell Stack section
#    julia         # Julia section
#    docker        # Docker section
#    aws           # Amazon Web Services section
#    venv          # virtualenv section
    conda         # conda virtualenv section
#    pyenv         # Pyenv section
#    dotnet        # .NET section
#    ember         # Ember.js section
#    kubecontext   # Kubectl context section
    exec_time     # Execution time
    line_sep      # Line break
#    battery       # Battery level and status
    vi_mode       # Vi-mode indicator
    jobs          # Background jobs indicator
    exit_code     # Exit code section
    char          # Prompt character
)

SPACESHIP_HOST_SHOW_FULL="true"
